# Generated by Django 6.0.5 on 2026-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('stock', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('product', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
