# Generated by Django 6.0.5 on 2026-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ManyToManyField(db_index=True, to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
